### ISSUE TITLE
[FEATURE] Load from CDN

### ISSUE THREAD

**Issue by jminardi** [DivanteLtd/storefront-ui#1020]
**Describe how this feature will help us improve**
I like to load as much as possible through CDNs as it decreases my personal bandwidth and increases the chance of a cache hit for my users.

**Describe the solution you'd considered**
UNPKG (unpkg.com) provides CDN service for all packages on NPM. If the NPM package included minimized js and compiled CSS then we would be able to load it using the UNPKG CDN.

**Additional context**
Maybe I am missing something that would make this impossible or not useful.

**Comment by erictuvesson** [comment]
Are you talking about putting the library on a global CDN for example how many libraries are doing?
Example: [Google's Hosted Libraries](https://developers.google.com/speed/libraries)

There is both pros and cons of doing that, the biggest downside is security.

**Comment by EduardDopler** [comment]
Hi @jminardi, performance improvements via CDN for internal JS are a common myth, see e.g. https://csswizardry.com/2019/05/self-host-your-static-assets/ (_"cross domain caching"_), in fact, hosting crucial JS externally will most likely **degrade** performance.

As Storefront UI is _very_ crucial for sites using it (often you don't see a single pixel while it is loading), I'd strongly encourage everybody to self-host it and integrate it in your code base (as a dependency) and workflow/build flow. Then then there is little be concerned about because SFUI is strongly 🚀 performance-driven 😉

AFAIK there are no plans to pre-compile SFUI for now. @filrak correct me if I'm wrong.
