### ISSUE TITLE
[ Mobile / Desktop ] Create SfHero

### ISSUE THREAD

**Issue by leomp12** [DivanteLtd/storefront-ui#149]
[Designs on Figma](https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=151%3A0)

![Screenshot_2019-06-08 Figma](https://user-images.githubusercontent.com/10326572/59154636-423e3a00-8a4d-11e9-8ec1-752222423a07.png)

Should use Glidejs to handle slide, take a look on SfGallery or SfCarousel as examples.

# Proposed API

## Props

```js
{
  /**
   * List of banners:
   * array of nested objects with format: `[{ image, title, subtitle, cta, route }]`
   */
  banners: {
    type: Array,
    required: true
  },
  /**
    * Glide slider options (https://glidejs.com/docs/options/)
    */
  sliderOptions: {
    type: Object,
    default() {
      return {
        type: "slider",
        autoplay: 8000,
        rewind: true
      };
    }
  }
}
```
On banner object, only `image` (img src) should be required.

## Slots

- `default`: the content itself, overwriting each banner image, should bind `banner` object;
- `next`: next banner icon (arrow right by default), should bind `isFirst` boolean;
- `previous`: previous banner icon (arrow left by default), should bind `isLast` boolean;
- `bullets`: pagination bullets, should bind `total` and `current` (numbers);

## Events

```js
this.$emit("click", banner.route);
```

Please mind that it's **just a proposal**. We're open to discussion regarding component API.
:grin:

**Comment by bahdcoder** [comment]
@leomp12 API looks good IMO. Some ideas: 

- I think `SfHero` would be a better name for this component, since `SfSlider` is more suitable for a number range component if we ever have one. So slider would work for something like in the image below:

![Screen Shot 2019-06-10 at 12 37 52 AM](https://user-images.githubusercontent.com/19477966/59165722-0f14ad00-8b18-11e9-8c82-45201f8ad41c.png)

- Would we be interested in supporting/exposing more of the options and events provided by Glide ? Some good options like `startAt`, `perView`, `autoPlay` etc and some good events like `move`. 

Oh, I call dibs on this one 😅

**Comment by leomp12** [comment]
@bahdcoder you're right, thanks!
I had forgotten the prop for glidejs options, I'll edit the issue.

**Comment by filrak** [comment]
The API looks great, thanks @leomp12 . maybe we can use SfCallToAction as a base for a slide?

**Comment by leomp12** [comment]
@filrak not sure, designs aren't the same, or are you planning to adapt `SfCallToAction` for that?

**Comment by leomp12** [comment]
But maybe we can use `buttonText` as banner object property (instead of `cta`) to be similar to `SfCallToAction` api, sounds better?

**Comment by filrak** [comment]
@leomp12 I was just thinking more about copying some styles to have a quicker setup

**Comment by leomp12** [comment]
Ah sure @filrak
