### ISSUE TITLE
[FEAT] MegaMenu component

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#18]
Create mega menu component (desktop only)
This component is only a wrapper for other components so the task does not involve creating  the components inside of it.

![image](https://user-images.githubusercontent.com/15185752/54913026-25847280-4ef2-11e9-9157-08b01324ac7d.png)

Proposed API:
- just a default slot

Visibility properties shouldn't be a part of the component itself so the task is to make static MegaMenu component without any content, just a slot + write basic unit tests:
- if it renders
- if the slot content is rendered.

Designs: https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=99%3A0

**Comment by aniamusial** [comment]
I'm taking this one

**Comment by rmakara** [comment]
@aniamusial the best! :)

**Comment by SebastienPoncelet** [comment]
Hello @aniamusial,

Have checked the `m-menu.vue` component and it imports several elements like this: `import { SfMegaMenu, SfList, SfMenuItem, SfBanner } from '@storefront-ui/vue'`.

However it seems that the imports do not work due to `@storefront-ui/vue` that can't be resolved, no matter if `yarn install` has been executed.

Is there something missing in order to use the mega menu?
Where can I see what the elements such as `SfMegaMenu` look like?


Best regards,

Sebastien
