### ISSUE TITLE
[Improvement] - Change SfCounter to SfQuantitySelect

### ISSUE THREAD

**Issue by mayashavin** [DivanteLtd/storefront-ui#263]
Scopes:
1. Make SfCounter better in UI
2. Make it selectable input (can manual type instead of just select from dropdown)
3. Should receive a list of options (for example: 1,2,5,10, custom...)

**Comment by filrak** [comment]
Also maybe we can adjust naming somehow? ProductCounter?

**Comment by leomp12** [comment]
It's not another component? Sounds good to have a quantity select input, I think we must also have a number input (manual input with buttons).

**Comment by filrak** [comment]
@leomp12 it's this one
![image](https://user-images.githubusercontent.com/15185752/62195940-5a5f7500-b37d-11e9-991a-34853a94939b.png)

**Comment by leomp12** [comment]
@filrak yup, I think this component was changed on designs, but imo we should keep `SfCounter` as is, maybe edit the icons or change something visual but keep the component functionality.

Imo this select input should be another component, or it can be named `SfCounter` and current `SfCounter` can be renamed to `SfInputNumber` for example.

I just think we must have a numbers only input with controls, because the quantity selector is good but I don't think will be the best fit always. So imo we should have both, and then I'm suggesting the implementation of a new component instead of improvements for SfCounter.

**Comment by mayashavin** [comment]
@leomp12 We can't rename `SfCounter` to `SfInputNumber` simply because the name doesn't stand for the purpose of the component. Currently, it serves as a counter (with </> button as a decrease/increase), and also receives an input number. 

Not sure we have any other use for this component other than being counter of a product quantity? We can have 2 mode - one is simply counter, and one is an advance mode with select dropdown as proposed. There is no need for 2 components that basically does almost the same thing.

@filrak wdyt?

**Comment by filrak** [comment]
Imho there is no other and it shouldn't be input number tbh. The standard SfInput will serve this purpose well as it's friendly for mobile devices aswell.

SfCounter can be even renamed to SfQuantityInput or sth similar.

**Comment by mayashavin** [comment]
@filrak So `SfQuantitySelect` maybe? @leomp12 wdyt?

**Comment by leomp12** [comment]
@mayashavin sorry for the delay.
`SfQuantitySelect` is good to me, wdyt about working as a select if quantity is integer and lower then a number prop (defaults to 10 or something...), if not, work as a number input?
