### ISSUE TITLE
Dealing with CSS vars for colors

### ISSUE THREAD

**Issue by leomp12** [DivanteLtd/storefront-ui#376]
We're handling theme customization with SCSS, which is good enough, but I think we can also support easy customization with CSS vars.

My suggestion is to set more color variations on `$colors-map` ([_colors.scss](https://github.com/DivanteLtd/storefront-ui/blob/master/packages/shared/styles/variables/_colors.scss)):

- `primary-light`
- `primary-lighter`
- `primary-lightest`
- `secondary-light`
- `secondary-lighter`
- `secondary-lightest`

**Then on component styles we just use those pre-set color variables with SCSS `map-get`.**

By doing that we can prevent using SCSS `lighten`/`darken`, then user can use CSS vars for colors by setting SCSS vars (without compilation errors):

```scss
$c-primary-light: var(--primary-light);
```

Note: I'm mentioning just lighter color scales because Imo when using lighten and darken it goes ambiguous, it gets hard to decide to use dark variations with default or light variations with default.

**Comment by leomp12** [comment]
Also, taking advantage that we would have to refactor component styles, would be good to clean up `_colors.scss` removing some variables.

For example, why we have `$c-accent-primary` and `$c-primary`? Why not just one?
I'm not sure either if we need `$c-pink-primary` or just `$c-danger` (same for info, warning...), wdyt?

**Comment by EduardDopler** [comment]
I agree with @leomp12.
Some things popping into my mind:
- Don't use actual colors in color variables (like "pink") but describe the intent ("warning", "hint", etc.)
- Use HSL instead of RGB.
  - Because https://www.sarasoueidan.com/blog/hex-rgb-to-hsl/
  - tl;dr While RGB values are meaningless for humans, from HSL values you can guess what's going on.
  - You immediately know which colors have the same saturation or brightness, which ones are "light" or "dark" and so on.
  - Example for grey (works even better with a specified color (=hue+saturation)): 
```scss
$white:  hsl(0, 0%, 100%);
$grey-1: hsl(0, 0%,  15%);
$grey-2: hsl(0, 0%,  30%);
$grey-3: hsl(0, 0%,  50%);
$grey-4: hsl(0, 0%,  70%);
$grey-5: hsl(0, 0%,  85%);
$black:  hsl(0, 0%,   0%);
```
- I personally also like the Material Design color system.
  - https://material.io/design/color/
  - There's no "base color" with lighter and darker variants but all colors are on a scale, e.g. "purple-500" for a vibrant purple, "purple 200" for a very light one, "purple 800" for a very dark one.
  - This makes it easier if there is also a dark theme, because normally (in a light theme) the light version of color is used for hints and other not important text, but in a dark theme the light version of color becomes more visible than the dark version. (I know, we don't have a dark theme; but... you never know 😛)
  - I also like that they have a "primary" color and a "primary variant" which is only a little bit different (can be used to signal a different state of on object (like selected, activated)). Same thing with "secondary" and "secondary variant".
  - And I like the naming of `$on-primary` for text/icons/lines etc. _when the background has the primary color_.

**Comment by leomp12** [comment]
Thanks @EduardDopler ! :)

I almost totally agree with you, just not sure about "primary variant", we would have to define conventions for which case to use primary and with case use variant, do you have it in mind?

And we already have `$c-on-primary` (same for others) for text/icons/lines etc..

**Comment by EduardDopler** [comment]
Concerning `$c-on-xxx`: oops 🙈 yes, I meant that. Great that we have that ^^
___
Concerning variants: I'd use it for everything where we alter the primary/secondary color by using `darken`/`lighten`. Like in `SfButton` where we use `background-color: lighten($button-background-color, 5)`. I'd like to define this color variant upfront in *_colors.scss* so it becomes reusable.
So the same color can be used for all active states, maybe for gradients (nice subtle gradients from primary to primary-variant).
That way we could get rid of all `darken`/`lighten` in the components code and have colors **only in the _colors.scss**. (Then you always know where the colors come from.)
If we continue altering our main colors inside component definitions, we may quickly end up with many different colors, scattered around many files.

But yeah, both approaches are common and have their pros and cons. I'm not too eager to implement these variants at all costs.

**Comment by leomp12** [comment]
Ah ok, sounds good!
