### ISSUE TITLE
[Bug] Environment Different

### ISSUE THREAD

**Issue by przspa** [DivanteLtd/storefront-ui#391]
All scripts in `packages/vue/scripts` work great on unix but not well on windows.

1. `packages/vue/package.json` in scripts we used unix `$npm_execpath`, this not work on windows
2. `packages/vue/scripts/create-vue-components-dosc.js` regexp used unix `\n` and it doesn't work on windows. On unix we used just `\n` and on windows we used `\r\n`. Try this `\r\n|\n` to fix it.

All scripts should work on both platforms and don't forget about Netlify :)

**Comment by EduardDopler** [comment]
Quick question @przspa (maybe @filrak)
In a refactor in the future, we can refactor the 2 files `set-styles-variables-*-path.js` and merge them, because they are almost identical. We could use function parameters, e.g.:
```js
function replaceStylesVariablesPath(from, to) { … }
```
and just call them with the proper params like `replaceStylesVariablesPath("../../../../sfui.scss", "../../vue/sfui.scss")` and vice versa.

It got lost in the [old PR](https://github.com/DivanteLtd/storefront-ui/pull/390/files) sorry.

And one more thing: Do the scripts now run on windows and linux? Without changes to the regexp? Or do I need to change something inside _create-vue-components-docs.js_?

**Comment by przspa** [comment]
@EduardDopler about regexp. Git on window auto change `lf` to `crlf`. 
I changed this behaviour in my git global config but maybe wy should use `.gitattributes` https://help.github.com/en/articles/configuring-git-to-handle-line-endings#per-repository-settings. 
What did you think about that? The second options are changed regexp, but I think `.gitattributes` looks like a better way. 
About refactor +1, thanks!

**Comment by EduardDopler** [comment]
@przspa Perfect, _.gitattributes_ is a great idea 👍  Would you add one or shall I do it?
