### ISSUE TITLE
Compare to vue-storefront and rtl support

### ISSUE THREAD

**Issue by j209** [DivanteLtd/storefront-ui#444]
Hi
What is difference between storefront-ui and Vue Storefront ?
And is there any plan for supporting rtl langs (such Arabic,Hebr,..) in storefront-ui?

**Comment by EduardDopler** [comment]
Hi @j209!

_**Vue Storefront**_ is an eCommerce ("e-shop") application, responsible for the front-end part of eCommerce. It is unique in a way because it is a thought as an PWA from the ground up, with high performance in mind. It plays nicely with "shop back-ends" like Magento. You can see how it is architectured on [its GitHub page](https://github.com/DivanteLtd/vue-storefront#the-architecture).

_**Storefront UI**_ (this repo) is an UI framework with highly customizable components, not only for _Vue Storefront_. Think of it as nicely designed UI components which you can use in your Vue application. We cherish performance and accessibility. You can read the docs about how you can [customize](https://docs.storefrontui.io/customization.html) them to any needs in various ways.

As far as I know, there shouldn't be any RTL-specific issues with the components. Can you give us an example?

Does this answer your question?

**Comment by j209** [comment]
Thanks for your quick response.
These are some vue farmeworks that support rtl cultures:

![image](https://user-images.githubusercontent.com/18129232/68540793-bab67780-03ac-11ea-9691-cc7d62413f08.png)

And for an example for testing rtl views you can see [Material Ui](https://material-ui.com/components/dialogs/) site and toggle right to left button on the toolbar.

![image](https://user-images.githubusercontent.com/18129232/68540962-cd31b080-03ae-11ea-8a13-af761f6059fd.png)

**Comment by filrak** [comment]
@j209 I think with `direction: rtl` everything should work just fine. There might be some cases like `SfBanner` where I'm not sure about this. It's worth checking for sure.

Maybe you want to contribute and do this by yourself? ;)

**Comment by GabiGlazberg** [comment]
Hey.
"direction: rtl" is not the best solution to do rtl ltr support. 
You need to build the design suitable for both direction and load this in the run time (not to compile this with the vue component).
This is a set of sass mixin that give the ability to do so: [bi app](https://github.com/anasnakawa/bi-app-sass)
 I have tried to do so but I didnt find a clean way to do it in vuejs. But i'm not a vue export.
Hope you will make it work, I love yours project
