### ISSUE TITLE
[BUG] SfIcon doesn't render all sizes and colors correctly

### ISSUE THREAD

**Issue by EduardDopler** [DivanteLtd/storefront-ui#488]
**Describe the bug**

**SfCircleIcon** allows the icon size to be set as pixel values (default value: 20px) but this doesn't work with **SfIcon** which is used internally. Although the SfIcon prop docs say that pixel values are allowed, those are stripped by the `computed` method in SfIcon. The size you enter is just added as a class, but such classes do not exit.
Also, the color you enter is just appended as a class name. So this works only for Sf-UI values (e.g. `primary`), too.

In the SfIcon stories you can only choose from options which correspond to Sf-UI colors and sizes. So those stories are fine (but still the SfIcon component docs (comments inside SfIcon.js) are misleading!). But the SfCircleIcon stories allow to enter invalid values.

**Comment by mayashavin** [comment]
@EduardDopler it is not really a bug. If you enter a color, it has to be HEX or RGB color since we check if the color follows the HEX and RGB format and SfIcon will check if the color is valid (even in HEX there is invalid color). Otherwise, it will translate as if it is a class color.
About the size, the same, you need to pass it as `20px`, or "100%" or "1rem". Check out `props [default]` in SfIcon. The size there is set as 24px, and not from the list.

I did mention these inside the documentation section of SfIcon.

In the documentation of SfIcon, there is a section for modifying the props - `props [default]` We need to change the title of this section correctly also. The same goes for SfCircleIcon, you can see there is a section where the icon is defined with 24px size also.

**Comment by EduardDopler** [comment]
@mayashavin @filrak 
I know this is already marked as resolved and the PR merged but I don't get this component, sorry 🙈  I checked the source before opening this bug and I thought I knew where the problem is; I just wanted to wait until the CircleIcon PR (#111) was merged because I think both components need to be addressed for this bug. Anyway, let me clarify the problem a little more:

**Prolog**
The docs/comments for SfIcon say that you can use
* normal CSS values for the color and the size (e.g. `red`, `#ff00ff` or `12px`, `3rem`) or
* SfUI values (e.g. `primary` or `xxl`).

The template of SfIcon looks like this:
```html
<div :class="['sf-icon', iconColor, iconSize]" ref="icon" v-on="$listeners">
  <slot v-bind="{ viewBox, iconPaths, icon }">
    <svg class="sf-icon-path" :viewBox="iconViewBox" preserveAspectRatio="none">
        <path :d="icon" v-for="(icon, index) in iconPaths" :key="index" style="height: 100%;"/>
    </svg>
  </slot>
</div>
```

You can see that `iconColor` and `iconSize` are inserted as CSS classes.
They are resolved via these `computed` methods:
```js
iconColor() {
  return !this.isDecimalOrHexColor
    ? `sf-icon--color-${this.color.trim()}`
    : this.color;
}
iconSize() {
  return this.isSFSizes ? `sf-icon--size-${this.size.trim()}` : "";
}
```

**Problem**
So when the `color` prop isn't a SfUI value, it is just inserted as a class as-is.
Similarly, when the `size` prop is no SfUI value, an empty string gets inserted.

**My Interpretation**
So I would say: **Either** the docs aren't correct (we allow only SfUI values, the rest results in garbage CSS classes or nothing) **or** the implementation isn't correct.
I would favor the latter because imho this could be easily solved: When the `size` or `color` is a SfUI value, insert the appropriate class (like now); when it is not, insert them **as a `:style` binding**.

wdyt?

---

**And why is this related to CircleIcon?**
Because in the **SfIcon** stories you can only select (from a select input) *valid SfUI values*. So the problem as described above doesn't show up. But in the **SfCircleIcon** stories you can enter *text values* like `24px` which are–according to the component docs of SfIcon–correct values but lead to the problem above.

---

If this is my misinterpretation, please let me now and close the bug again. For now, I'll reopen it because I think it is still broken (cf. [Story CircleIcon of this PR's state](https://deploy-preview-498--storefrontui-storybook.netlify.com/?path=/story/atoms-circleicon--default)).

**Comment by mayashavin** [comment]
@EduardDopler You didn't look at the component implementation throughout. Before on `mounted`, we do set the CSS variable of `icon-color` and `icon-style` if the color and size passed is not standard (according to SFUI). `color` and `size` computed is just the class properties in case it does go according to SFUI. The bug before was that since we only set CSS variable of `icon-color` and `icon-size` one time on mounted if the component is updated with different color and size, it won't update the right color and size.

<img width="838" alt="Screen Shot 2019-12-05 at 11 58 29" src="https://user-images.githubusercontent.com/6650139/70233886-21d70a00-1768-11ea-8bb3-7ecac293b557.png">

You also need to look at the Storybook, we do have 3 stories for SfIcon, and one of them dedicated for these customized variables. 
<img width="838" alt="Screen Shot 2019-12-05 at 11 58 29" src="https://user-images.githubusercontent.com/6650139/70233973-4d59f480-1768-11ea-8172-4fc6dc674b68.png">

In this screenshot, as you can see, passing the prop `24px` and non-standard color is working still. 

Similar in SfCircleIcon, I passed the default value of `sizeIcon` as 100% and it does show in the component. I don't see why there is a bug as you describe except what I wrote above.

I'm closing it as it's not broken.
