### ISSUE TITLE
[ Mobile/Dsktop ] Adjust SfHeader to current two-ways of customization format

### ISSUE THREAD

**Issue by aniamusial** [DivanteLtd/storefront-ui#51]
- Image in SfHeader should be customizable via url - see #4 for reference. 

- Missing props for text

- IMO content alignment (left/right/top) shouldn't be done with slots, but passed as a prop instead - what do you think?

**Comment by leomp12** [comment]
I've talked with @filrak about this component, imho we should keep the slots to handle markup replacement, but should also add props to make easier more common customization, such as the logo src.

**Comment by leomp12** [comment]
I think we should also populate the slots with intended components, following the proposed designs as default, but first we may need to create the respective atoms and molecules components.

**Comment by filrak** [comment]
I think the header is prty hard and complex case since it's used in many contexts so slots are the natural way of doing this.

For example we might want to use button instead of icon, or want to use label instead of logo (all of those are in the designs)

I still need to figure out how to move mobile/desktop design into this component since they are totally different so let's leave it like this for now ok?
