### ISSUE TITLE
[FEATURE] Detect isMobile without register a lot evenListeners in components

### ISSUE THREAD

**Issue by pspaczek** [DivanteLtd/storefront-ui#581]
Now we used a lot of listeners to detect isMobile in JS, probably we can do that better without eventListeners hell

**Comment by DonNicoJs** [comment]
I'll take this!

**Comment by pspaczek** [comment]
Awesome @DonNicoJs 🙏

**Comment by DonNicoJs** [comment]
So i want to write down few ideas so that we can discuss here:

## 1)  Create a mixin 
to DRY up the logic which is repeated a lot in the code ( this does not solve the issue but alleviate the copy pastaed code )

### Pro
- DRYer code
- Easy to maintainer
### Con
- does not solve issue of lots of event handlers
- Mixins may make it harder for customisation first principle 

## 2) Create an 'external' service

The service will 
- add one event listener to detect resize and determine if is mobile
- return a vue observable (https://vuejs.org/v2/api/#Vue-observable) that we can digest normally in the components
- import the service in all the components
- make sure the service is a singleton

### Pro
- 1 event
- 1 single source of truth
- DRY code
### Con
- a bit of boilerplate for each component
- Needs to be documented

## 3) Pollute the window object

Same idea as above, instead of exporting a service add a scoped property to window like `$sfUI` 

### Pro
- Same as 2 
- No need to import everywhere
### Con
- SSR gotchas
- polluting the window object is BAD
- Needs to be documented

## 4) Combine 1 and 2 

- Create the service
- consume and expose it trough a mixin
-  add mixin to components

### Pro
- Same as 2 
- Only import mixin
### Con
- Mixins may make it harder for customisation first principle 
- Needs to be documented

**Comment by pspaczek** [comment]
Sorry @DonNicoJs The Second proposition looks awesome without mixin 👍🚀for me is good way to do that.

**Comment by DonNicoJs** [comment]
@pspaczek Perfect I will proceed that direction and make a PR in the coming days!

**Comment by pspaczek** [comment]
@DonNicoJs awesome and all best in the new year

**Comment by EduardDopler** [comment]
@DonNicoJs I also favor option 2. And—once Vue 3 is released—this is a textbook example for the [composition API](https://vue-composition-api-rfc.netlify.com/) and its `ref` (or `reactive`) concept!  🙌

**Comment by aniamusial** [comment]
@DonNicoJs hi, how is the work going? :)

**Comment by DonNicoJs** [comment]
@aniamusial Sorry for the slow slow work here, I am planning to finish this over this WE :) Will have a PR ready by monday!

**Comment by pspaczek** [comment]
@DonNicoJs don't sorry :) then we waiting for it, thanks for the update 💚
