### ISSUE TITLE
[BUG] color-x css modifiers have white bg with white text

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/storefront-ui#700]
For `SfButton` but please check other components:
![image](https://user-images.githubusercontent.com/15185752/73105433-4abe8480-3ef9-11ea-9862-0c5c777c0069.png)
hover:
![image](https://user-images.githubusercontent.com/15185752/73105439-501bcf00-3ef9-11ea-9206-c04d8707d9ff.png)

**Comment by aniamusial** [comment]
@peoray how is the work going? :)

**Comment by peoray** [comment]
Right after I send in a PR tonight for the important issue :)
Again, thanks for the reminder and sorry for any delay it's causing

**Comment by Trapdafifou** [comment]
i don't reproduce the issue anymore has it been fixed ? Background is now dark at hover with white typo.

**Comment by martaradziszewska** [comment]
@Trapdafifou bug is still there :) @peoray Are you still want to work on it?

**Comment by peoray** [comment]
@martaradziszewska Yes, although I'm not sure I'm doing it right. I'll post updates and issues I'm having when I get home from work :)

**Comment by peoray** [comment]
@martaradziszewska. Please how can I reproduce this issue?

**Comment by martaradziszewska** [comment]
@peoray To reproduce it you should:
1. Go to https://storybook.storefrontui.io/?path=/story/atoms-button--common
2. Choose one of color modifiers e.g. color-danger
3. Hover on button and see that background color is too light compared with text color

I will take it also because it's connected with #777  :)
